# Generated by Django 5.0.1 on 2024-01-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('kinopoisk_rating', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemingle.show')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='sources',
            field=models.ManyToManyField(to='moviemingle.source'),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('kinopoisk_rating', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('sources', models.ManyToManyField(to='moviemingle.source')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviemingle.season')),
                ('sources', models.ManyToManyField(to='moviemingle.source')),
            ],
        ),
    ]
