# Generated by Django 5.0.1 on 2024-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemingle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
